cmdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from index.views import index, login_view, logout, error
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^index/$', index),
    url(r'^index.html$', index),
    url(r'^jigui/', include('jigui.urls')),
    url(r'^login.html$', login_view),
    url(r'^login/$', login_view),
    url(r'^logout.html$', logout),
    url(r'^error.html$', error),
    url(r'^host/', include('hostinfo.urls')),
    url(r'^sh/', include('sh.urls')),
]

sh/urls.py
from django.conf.urls import url
from sh.views import sh,shadd,shedit,shinfo,shdel,shdelall,shell,shell_sh


urlpatterns = [
    url(r'^sh.html$', sh,name="sh"),
    url(r'^shadd.html$', shadd,name="sh_add"),
    url(r'^shedit-(?P<nid>\d+).html$', shedit,name="sh_edit"),
    url(r'^shinfo-(?P<nid>\d+).html$', shinfo, name="sh_info"),
    url(r'^shdel.html$', shdel, name="sh_del"),
    url(r'^shalldel.html$', shdelall, name="sh_delall"),
    url(r'^shell-(?P<nid>\d+).html$', shell, name="shell"),
    url(r'^shell.html$', shell_sh, name="shell_sh"),
    # url(r'^shdel$', host_del,name='host_del'),
    # url(r'^shupdate$', hostupdate,name="hostupdate"),
    # url(r'^sh-del.html$', hostall_del),
    # url(r'^sh-(?P<nid>\d+).html$', host_show, name='sh_info'),

]

sh/models.py
from django.db import models



TOOL_RUN_TYPE = (
    (0, 'shell'),
    (1, 'python'),
    (2, 'yml'),
)

# class ToolsTypes(models.Model):
#     name = models.CharField(max_length=255, verbose_name='类型名称')
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = "工具类型"
#         verbose_name_plural = verbose_name


class ToolsScript(models.Model):
    name = models.CharField(max_length=255, verbose_name='工具名称')
    tool_script = models.TextField(verbose_name='脚本')
    # tools_type = models.ForeignKey(ToolsTypes, verbose_name='工具类型')
    # tool_run_type = models.CharField(max_length=255, verbose_name='脚本类型')
    tool_run_type = models.IntegerField(choices=TOOL_RUN_TYPE,verbose_name='脚本类型',default=0)
    comment = models.TextField(verbose_name='工具说明', null=True, blank=True)
    ctime = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')
    utime = models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')
    
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "ToolsScript"
        verbose_name = "工具"
        verbose_name_plural = verbose_name
        





sh/views.py
from  django.shortcuts import render, redirect, HttpResponse
from sh.models import ToolsScript
from hostinfo.models import Host,History
import json,os
from django.contrib.auth.decorators import permission_required, login_required
from djcelery import models as celery_models


import sys
sys.path.append('../hostinfo/ansible_runner/')


from   hostinfo.ansible_runner.runner      import AdHocRunner,PlayBookRunner
from   hostinfo.ansible_runner.callback    import CommandResultCallback


@login_required(login_url="/login.html", )
def sh(request):  ##首页
    sh = ToolsScript.objects.filter(id__gt=0).order_by('-id')
    return render(request, 'sh/sh.html', {"sh_list":sh, })

@login_required(login_url="/login.html")
@permission_required('sh.add_ToolsScript',login_url='/error.html')
def shadd(request):  #添加
    if request.method == "POST":
        name = request.POST.get('name', None)
        tool_script = request.POST.get('tool_script', None)
        tool_run_type = request.POST.get('tool_run_type', None)
        comment = request.POST.get('comment', None)
        obj = ToolsScript.objects.create(name=name,tool_script=tool_script,tool_run_type=tool_run_type,comment=comment)
        msg = "添加成功"
        return render(request, 'sh/shadd.html', {'msg': msg ,})
    else:
        return render(request, 'sh/shadd.html',)
    
    
    
@login_required(login_url="/login.html")
@permission_required('sh.change_ToolsScript',login_url='/error.html')
def shedit(request, nid):   #编辑
    if request.method == "GET":
        obj1 = ToolsScript.objects.filter(id=nid)
        return render(request, 'sh/shedit.html',{'obj':obj1})

    elif request.method == "POST":
        
        name = request.POST.get('name', None)
        tool_script = request.POST.get('tool_script', None)
        tool_run_type = request.POST.get('tool_run_type', None)
        comment = request.POST.get('comment', None)

        obj1 = ToolsScript.objects.filter(id=nid).first()
        obj1.name=name
        obj1.tool_script=tool_script
        obj1.tool_run_type=tool_run_type
        obj1.comment = comment
        obj1.save()
        
        return redirect('/sh/sh.html')


@login_required(login_url="/login.html")
def shinfo(request, nid):  # 查看
    if request.method == "GET":
        obj1 = ToolsScript.objects.filter(id=nid)

        return render(request, 'sh/shinfo.html', {'obj': obj1})


@login_required(login_url="/login.html")
@permission_required('sh.delete_ToolsScript',login_url='/error.html')
def shdel(request):  # 删除
    ret = {'status': True, 'error': None, 'data': None}
    if request.method == "POST":
        id = request.POST.get('id',None)
        obj1 = ToolsScript.objects.filter(id=id).delete()
        return HttpResponse(json.dumps(ret))

@login_required(login_url="/login.html")
@permission_required('sh.delete_ToolsScript',login_url='/error.html')
def shdelall(request):##批量删除
    ret = {'status': True, 'error': None, 'data': None}
    if  request.method == "POST":
             ids = request.POST.getlist('id')
             idstring = ','.join(ids)
             ToolsScript.objects.extra(where=['id IN (' + idstring + ')']).delete()
             return HttpResponse(json.dumps(ret))




@login_required(login_url="/login.html")
def shell(request,nid):  ##执行脚本页面
    if  request.method=="GET":
        obj = Host.objects.filter(id__gt=0)
        sh = ToolsScript.objects.filter(id=nid)
      
        return  render(request,'sh/shell.html',{"host_list": obj,"sh":sh })


@login_required(login_url="/login.html")
def shell_sh(request):  ##执行脚本-执行
    ret = {'status': True, 'data': None}
    
    if request.method == 'POST':
        try:
            host_ids = request.POST.getlist('id', None)
            sh_id = request.POST.get('shid', None)
            user = request.user

            if not host_ids:
                error1 = "请选择主机"
                ret = {"error": error1, "status": False}
                return HttpResponse(json.dumps(ret))
                
            idstring = ','.join(host_ids)
            
            host = Host.objects.extra(where=['id IN (' + idstring + ')'])
            sh = ToolsScript.objects.filter(id=sh_id)
            
            for s in sh:
                if s.tool_run_type == 0:
                    with  open('sh/shell/test.sh', 'w+') as f:
                        f.write(s.tool_script)
                        a = 'sh/shell/{}.sh'.format(s.id)
                    os.system("sed 's/\r//'  sh/shell/test.sh >  {}".format(a))
                    
                elif s.tool_run_type == 1:
                    with  open('sh/shell/test.py', 'w+') as f:
                        f.write(s.tool_script)
                        p = 'sh/shell/{}.py'.format(s.id)
                    os.system("sed 's/\r//'  sh/shell/test.py >  {}".format(p))
                elif s.tool_run_type ==  2:
                    with  open('sh/shell/test.yml', 'w+') as f:
                        f.write(s.tool_script)
                        y = 'sh/shell/{}.yml'.format(s.id)
                    os.system("sed 's/\r//'  sh/shell/test.yml >  {}".format(y))
                else:
                        ret['status'] = False
                        ret['error'] = '脚本类型错误,只能是shell、yml、python'
                        return HttpResponse(json.dumps(ret))
        

                data1 = []
                for h in host:
                    try:
                        data2={}
                        assets = [
                            {
                                "hostname": h.hostname,
                                "ip": h.ip,
                                "port": h.port,
                                "username": h.username,
                                "password": h.password,
                            },
                        ]

                        history = History.objects.create(ip=h.ip, root=h.username, port=h.port, cmd=s.name, user=user)
                        if s.tool_run_type == 0 :
                            task_tuple = (('script', a),)
                            hoc = AdHocRunner(hosts=assets)
                            hoc.results_callback = CommandResultCallback()
                            r = hoc.run(task_tuple)
                            data2['ip']=h.ip
                            data2['data']=r['contacted'][h.hostname]['stdout']
                            data1.append(data2)
                        elif s.tool_run_type == 1 :
                            task_tuple = (('script', p),)
                            hoc = AdHocRunner(hosts=assets)
                            hoc.results_callback = CommandResultCallback()
                            r = hoc.run(task_tuple)
                            data2['ip'] = h.ip
                            data2['data'] = r['contacted'][h.hostname]['stdout']
                            data1.append(data2)
                        elif s.tool_run_type ==  2 :
                            play = PlayBookRunner(assets, playbook_path=y)
                            b = play.run()
                            print(b)
                            data2['ip'] = h.ip
                            data2['data'] = b['plays'][0]['tasks'][1]['hosts'][h.hostname]['stdout'] + b['plays'][0]['tasks'][1]['hosts'][h.hostname]['stderr']
                            print(data2['data'])
                            
                            
                            print(data2)
                            data1.append(data2)
                        else:
                            data2['ip'] = "脚本类型错误"
                            data2['data'] = "脚本类型错误"
                    except  Exception as  e:
                        data2['ip'] = h.ip
                        data2['data'] ="账号密码不对，请修改 {}".format(e)
                        data1.append(data2)
                        
                ret['data'] = data1
                print(ret)
                return HttpResponse(json.dumps(ret))
        except Exception as e:
               ret['status'] = False
               ret['error'] = '未知错误 {}'.format(e)
               return HttpResponse(json.dumps(ret))




templates/sh/sh.html
{% extends "base.html" %}

{% block header-css %}
{% endblock %}




{% block page-content-title %} 脚本 {% endblock %}

{% block page-nav-tab %}
    <ol class="breadcrumb">
        <li>
            <a href="../index.html">首页</a>
        </li>
        <li>
            <a href="sh.html">详情</a>
        </li>
        <li class="active">
            <strong>脚本</strong></li>
    </ol>
{% endblock %}



{% block page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">


        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>机柜 </h5>
                        <div class="ibox-tools">
                            <a class="collapse-links">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">配置选项 1</a>
                                </li>
                                <li><a href="#">配置选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>

                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">


                            {% if    perms.sh.add_toolsscript %}
                                <a type="button" class="btn btn-primary " href="{% url    'sh_add' %}">
                                添加
                            </a>{% endif %}
                                 {% if    perms.sh.delete_toolsscript %}
                                <a class="btn btn-danger" data-toggle="modal"
                                   data-target="#myModa5">批量删除
                                </a>
                        {% endif %}
                            <form id="del_form_sh" class="form-horizontal">


                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>

                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>

                                        <th>工具名称</th>
                                        <th>脚本类型</th>
                                        <th>工具说明</th>
                                        <th>更新时间</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for row  in sh_list %}
                                        <tr class="gradeX" nid="{{ row.id }}"
                                            name="{{ row.name }}">

                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td><a href="/sh/shinfo-{{ row.id }}.html">{{ row.name }}</a></td>
                                            <td>{% ifequal row.tool_run_type  0 %}shell {% endifequal %}
                                            {% ifequal row.tool_run_type  1 %} python {% endifequal %}
                                               {% ifequal row.tool_run_type  2 %} yml {% endifequal %}
                                            </td>
                                            <td>{{ row.comment }}</td>
                                            <td>{{ row.utime }}</td>
                                            <td noWrap>
                                                <a href="/sh/shinfo-{{ row.id }}.html" type="button"
                                                   class="btn btn-primary">
                                                    查看 </a>

                                             {% if    perms.sh.change_toolsscript %}
                                                <a href="/sh/shedit-{{ row.id }}.html" type="button"
                                                   class="btn  btn-warning">
                                                    编辑 </a> {% endif %}
                                              {% if    perms.sh.delete_toolsscript %}        <a type="button" class="btn btn-danger  sh_del" data-toggle="modal"
                                                   data-target="#myModa6">
                                                    删除 </a>           {% endif %}
                                              <a type="button" class="btn btn-primary "  href="shell-{{ row.id }}.html"
                                              >
                                                    执行 </a>


                                            </td>

                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>
                        </div>

                    </div>
                </div>
            </div>


        </div>

        <div class="modal inmodal" id="myModa5" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content animated fadeIn">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span
                                aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <i class="fa fa-clock-o modal-icon"></i>
                        <h4 class="modal-title">批量删除</h4>
                        <span id="error2" style="color:red;"></span>
                        <small></small>
                    </div>
                    <form id="del_form">
                        <div class="modal-body">


                            <p><strong>确定删除？</strong></p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-white" data-dismiss="modal">关闭</button>
                            <a class="btn btn-danger shall_del ">批量删除</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <div class="modal inmodal" id="myModa6" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content animated fadeIn">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span
                                aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <i class="fa fa-clock-o modal-icon"></i>
                        <h4 class="modal-title">删除</h4>
                        <span id="error3" style="color:red;"></span>
                        <small></small>
                    </div>
                    <form id="del_form1">
                        <div class="modal-body">

                            <div class="form-group"><input type="text" name="id" style="display:none"/></div>
                            <p><strong>确定删除？</strong></p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-white" data-dismiss="modal">关闭</button>
                            <a class="btn btn-danger jigui_del " id="sh_del">删除</a>

                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>



{% endblock %}


{% block  js %}
    <script>


        $(function () {


            $('.shall_del').click(function () {
                $.ajax({
                    url: "/sh/shalldel.html",
                    type: 'POST',
                    data: $('#del_form_sh').serialize(),
                    success: function (data) {
                        var obj = JSON.parse(data);
                        if (obj.status) {
                            location.reload()
                        }
                    }

                })
            });


            $('.sh_del').click(function () {
                var id = $(this).parent().parent().attr('nid');
                var name = $(this).parent().parent().attr('name');
                $('#del_form1').find('input[name="id"]').val(id);

            });


            $('#sh_del').click(function () {
                $.ajax({
                    url: "/sh/shdel.html",
                    type: 'POST',
                    data: $('#del_form1').serialize(),
                    success: function (data) {
                        var obj = JSON.parse(data);
                        if (obj.status) {
                            location.reload()
                        } else {
                            $('#error3').text(obj.error);
                        }
                    }

                })


            })


        })


    </script>
{% endblock %}

templates/sh/shadd.html
{% extends "base.html" %}

{% block header-css %}
    {% endblock %}




{% block page-content-title %} 脚本添加 {% endblock %}

{% block page-nav-tab %}
 <ol class="breadcrumb">
                    <li>
                        <a href="../index.html">首页</a>
                    </li>
                    <li>
                        <a href="sh.html">详情</a>
                    </li>
                    <li class="active">
                        <strong>脚本添加</strong></li>
</ol>
{% endblock %}



{% block page-content %}

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">


            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5 style="color:red;"> {{ msg }} 脚本添加
                        </h5>
    <div class="ibox-tools">
                                <a class="collapse-links">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">配置选项 1</a>
                                    </li>
                                    <li><a href="#">配置选项 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" action="{% url  'sh_add' %}" method="post">
                         {% csrf_token %}

                            <div class="form-group"><label class="col-sm-2 control-label">工具名称</label>

                                <div class="col-lg-4 col-sm-6"><input type="text" class="form-control" name="name"  required="">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                       <div class="form-group"><label class="col-sm-2 control-label">脚本</label>

                                <div class="col-lg-6 col-sm-6"><textarea id="code2"  name="tool_script">
</textarea>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>

            <div class="form-group"><label class="col-sm-2 control-label"  >脚本类型</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><input type="radio"   value="0" id="optionsRadios1" checked="checked"  name="tool_run_type" required="">shell</label>
                                <label class="radio-inline"><input type="radio" value="1" id="optionsRadios2" name="tool_run_type" required="">python</label>
                                 <label class="radio-inline"><input type="radio" value="2" id="optionsRadios2" name="tool_run_type" required="">yml</label>
                            </div>
                        </div>
{#                              <div class="form-group"><label class="col-sm-2 control-label">脚本类型</label>#}
{##}
{#                                <div class="col-lg-4 col-sm-6"><input type="text" class="form-control" name="tool_run_type"  required="">#}
{#                                </div>#}
{#                            </div>#}
                            <div class="hr-line-dashed"></div>
                              <div class="form-group"><label class="col-sm-2 control-label">工具说明</label>

                                <div class="col-lg-4 col-sm-6"><input type="text" class="form-control" name="comment"  required="">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">

                                    <button class="btn btn-primary" type="submit">保存</button>
                                   <a  class="btn btn-white"  href="sh.html">取消</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}
 {% block  js %}


<script>


         $(document).ready(function(){


             var editor_two = CodeMirror.fromTextArea(document.getElementById("code2"), {
                 lineNumbers: true,
                 matchBrackets: true,
                 styleActiveLine: true
             });

        });
    </script>{% endblock %}

templates/sh/shedit.html
{% extends "base.html" %}

{% block header-css %}
    {% endblock %}




{% block page-content-title %} 脚本编辑 {% endblock %}

{% block page-nav-tab %}
 <ol class="breadcrumb">
                    <li>
                        <a href="../index.html">首页</a>
                    </li>
                    <li>
                        <a href="sh.html">详情</a>
                    </li>
                    <li class="active">
                        <strong>脚本编辑</strong></li>
</ol>
{% endblock %}



{% block page-content %}

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">


            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5 >  脚本编辑
                        </h5>
    <div class="ibox-tools">
                                <a class="collapse-links">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">配置选项 1</a>
                                    </li>
                                    <li><a href="#">配置选项 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                    </div>
                    <div class="ibox-content">

                      {% for  row  in  obj  %}
                        <form  class="form-horizontal" method="post"   action="/sh/shedit-{{ row.id }}.html">
                         {% csrf_token %}

                            <div class="form-group"><label class="col-sm-2 control-label">工具名称</label>

                                <div class="col-lg-4 col-sm-6"><input type="text" class="form-control" name="name"  required=""  value="{{ row.name }}">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                       <div class="form-group"><label class="col-sm-2 control-label">脚本</label>

                                <div class="col-lg-6 col-sm-6"><textarea id="code2"  name="tool_script"  >{{ row.tool_script }}</textarea>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>


                              <div class="form-group"><label class="col-sm-2 control-label">脚本类型</label>

                                <div class="col-lg-4 col-sm-6">


                            <div class="col-sm-10">
                                <label class="radio-inline"><input type="radio"    value="0" id="optionsRadios1"  {% ifequal row.tool_run_type  0 %}checked="checked"  {% endifequal %} name="tool_run_type" required="">shell</label>
                             <label class="radio-inline"><input type="radio" value="1"  {% ifequal row.tool_run_type  1 %}checked="checked"  {% endifequal %}  id="optionsRadios2" name="tool_run_type" required="">python</label>
                                <label class="radio-inline"><input type="radio" value="2" {% ifequal row.tool_run_type  2 %} checked="checked" {% endifequal %}  id="optionsRadios2" name="tool_run_type" required="">yml</label>

                            </div>
                        </div>



                                </div>

                            <div class="hr-line-dashed"></div>
                              <div class="form-group"><label class="col-sm-2 control-label">工具说明</label>

                                <div class="col-lg-4 col-sm-6"><input type="text" class="form-control"   value="{{ row.comment}}"  name="comment"  required="">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">

                                    <button class="btn btn-primary" type="submit"   >保存</button>
                                    <a  class="btn btn-white"  href="sh.html">取消</a>
                                </div>
                            </div>
                        </form>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}
 {% block  js %}


<script>


         $(document).ready(function(){


             var editor_two = CodeMirror.fromTextArea(document.getElementById("code2"), {
                 lineNumbers: true,
                 matchBrackets: true,
                 styleActiveLine: true
             });

        });
    </script>{% endblock %}